runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: views.app

libraries:
- name: jinja2
  version: latest
- name: MySQLdb
  version: "latest"

builtins:
- remote_api: on
  
env_variables:
    CLOUDSQL_CONNECTION_NAME: gcp-ac:us-east1:autocomplete-db
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD:''